nhnacademy-be4-InkBridge/frontend

- .github/workflows/maven.yml
로드밸런서를 위한 서버를 액션에 추가해준다
resolves #10  (이슈가 존재할 경우에만)
> [#10] chore: 로드밸런서를 위한 서버 추가

- .github/workflows/maven.yml
로드밸런서를 위한 GitAction 수정후 두번째 서버 미동작을 확인하여 수정
resolves #이슈번호 (이슈가 존재할 경우에만)
> [#10]fix: GitAction 설정 수정

- pom.xml
> [#10] refactor: security 의존성 삭제

- .github/workflows/maven.yml
GitAction 실행시 front서버 동시에 내려가는 문제 수정
resolves #10
> [#10] front서버 동시에 내려가는 문제 수정

- src/main/java/com/nhnacademy/inkbridge/front/controller/AdminIndexController.java
- src/main/resources/templates/admin/charts.html
- src/main/resources/templates/layouts/admin_layout.html
- src/main/resources/templates/layouts/main_layout.html
- src/main/resources/templates/member/index.html
template 수정
resolves #27 (이슈가 존재할 경우에만)
> [#27] refactor: template 수정

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/AccumulationRatePolicyAdaptor.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/AccumulationRatePolicyAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/AccumulationRatePolicyController.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/accumulationratepolicy/AccumulationRatePolicyCreateRequestDto.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/accumulationratepolicy/AccumulationRatePolicyReadResponseDto.java
- src/main/java/com/nhnacademy/inkbridge/front/service/AccumulationRatePolicyService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/AccumulationRatePolicyServiceImpl.java
- src/main/resources/templates/admin/accumulation_policies.html
1. 현재 적용 적립률 정책 조회
2. 전체 적립률 변경 내역 조회
3. 적용할 적립률 정책 생성
resolves #35
> [#35] 적립률 정책 페이지 구현

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/DeliveryPolicyAdaptor.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/DeliveryPolicyAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/DeliveryPolicyController.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/deliverypolicy/DeliveryPolicyCreateRequestDto.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/deliverypolicy/DeliveryPolicyReadResponseDto.java
- src/main/java/com/nhnacademy/inkbridge/front/service/DeliveryPolicyService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/DeliveryPolicyServiceImpl.java
- src/main/resources/templates/admin/delivery_policies.html
- src/main/resources/templates/layouts/admin_layout.html
1. 적용중인 배송비 정책 조회
2. 전체 배송비 정책 변경 내역 조회
3. 배송비 정책 생성
resolves #33
> [#33] 배송비 정책 페이지 구현

- src/main/java/com/nhnacademy/inkbridge/front/dto/book/AuthorReadResponseDto.java
> [#45] feat: AuthorReadResponseDto

- src/main/java/com/nhnacademy/inkbridge/front/dto/book/BookAdminReadResponseDto.java
refactor: BookAdminReadResponseDto
resolves #45 (이슈가 존재할 경우에만)
> [#45] refactor: BookAdminReadResponseDto

- src/main/java/com/nhnacademy/inkbridge/front/controller/AdminBookController.java
refactor: AdminBookController
resolves #45 (이슈가 존재할 경우에만)
> [#45] refactor: AdminBookController

- src/main/resources/application.properties
> setting: properties 설정

- src/main/java/com/nhnacademy/inkbridge/front/jwt/service/CustomUserDetailService.java
> [DEPLOY] 로그 추가한 배포

- src/main/resources/application.properties
> [DEPLOY] active profile 변경한 배포

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/DeliveryPolicyAdaptor.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/DeliveryPolicyAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/deliverypolicy/DeliveryPolicyAdminReadResponseDto.java
- src/main/java/com/nhnacademy/inkbridge/front/service/DeliveryPolicyService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/DeliveryPolicyServiceImpl.java
- src/main/resources/templates/admin/delivery_policies.html
배송비 정책 조회 url 분리.
현재 정책 조회 readResponseDto 변경일자 제외
resolves 
- #33
> [#33] 배송비 정책 admin url 분리

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/PointPolicyAdaptor.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/PointPolicyAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/PointPolicyTypeAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/PointPolicyAdminController.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/pointpolicy/PointPolicyAdminReadResponseDto.java
- src/main/java/com/nhnacademy/inkbridge/front/service/PointPolicyService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/PointPolicyServiceImpl.java
포인트 정책 admin 경로 설정 및 유형 번호로 적용 정책 조회 기능 추가
resolves 
- #21 (이슈가 존재할 경우에만)
> [#21] 포인트 정책 admin 경로 설정 및 유형 번호로 적용 정책 조회 기능 추가

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/AccumulationRatePolicyAdaptor.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/AccumulationRatePolicyAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/AccumulationRatePolicyAdminController.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/accumulationratepolicy/AccumulationRatePolicyAdminReadResponseDto.java
- src/main/java/com/nhnacademy/inkbridge/front/service/AccumulationRatePolicyService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/AccumulationRatePolicyServiceImpl.java
- src/main/resources/templates/admin/accumulation_policies.html
1. 적립률 정책 admin 경로 분리 
2. 적용 적립률 정책 조회 변경일자 삭제
resolves 
- #35 (이슈가 존재할 경우에만)
> [#35] 적립률 정책 admin 경로 분리 및 적용 적립률 정책 조회 변경일자 삭제

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/IndexAdaptor.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/IndexAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/IndexController.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/IndexRestController.java
- src/main/java/com/nhnacademy/inkbridge/front/service/IndexService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/IndexServiceImpl.java
- src/main/resources/static/js/book.js
- src/main/resources/static/js/bookform.js
> [#37] refactor: 배열로 수정

- src/main/java/com/nhnacademy/inkbridge/front/utils/CommonUtils.java
> [#72] 미디어 타입 헤더 추가

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/MemberAdaptorImpl.java
> [#72] 회원가입 경로 테스트했던거 다시 수정

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/TagAdaptor.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/TagAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/AdminTagController.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/tag/Tag.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/tag/TagCreateRequestDto.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/tag/TagCreateResponseDto.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/tag/TagDeleteResponseDto.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/tag/TagUpdateRequestDto.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/tag/TagUpdateResponseDto.java
- src/main/java/com/nhnacademy/inkbridge/front/exception/TagException.java
- src/main/java/com/nhnacademy/inkbridge/front/service/TagService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/TagServiceImpl.java
- src/main/resources/templates/admin/tag-list.html
⛑️ 작업 내용
❓ 리뷰 포인트
🧾 관련 이슈
resolves https://github.com/nhnacademy-be4-InkBridge/frontend/issues/19
> [#19] 테그 레이아웃

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/AccumulationRatePolicyAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/DeliveryPolicyAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/OrderAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/PointPolicyAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/PointPolicyTypeAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/WrappingAdaptorImpl.java
front 배포
resolves #이슈번호 (이슈가 존재할 경우에만)
> [DEPLOY] front 배포

- src/main/java/com/nhnacademy/inkbridge/front/jwt/filter/CustomJwtAuthenticationFilter.java
MemberId contextholder에 넣을 때 String type으로 변환
resolves #72 (이슈가 존재할 경우에만)
> [#72] MemberId contextholder에 넣을 때 String type으로 변환

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/CouponAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/AdminCouponController.java
쿠폰 페이지 접속안되는 문제 수정
createHeader()메소드 사용
resolves 
- #88
- #29 
- #41 
- #43
> #88 fix: 쿠폰 페이지 접속안되는 문제 수정

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/TagAdaptorImpl.java
> [#91] tag 헤더 추가

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/AddressAdaptor.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/AddressAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/TagAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/AddressController.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/address/AddressCreateRequestDto.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/address/AddressReadResponseDto.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/address/AddressUpdateRequestDto.java
- src/main/java/com/nhnacademy/inkbridge/front/enums/AddressMessageEnum.java
- src/main/java/com/nhnacademy/inkbridge/front/exception/ValidationException.java
- src/main/java/com/nhnacademy/inkbridge/front/service/AddressService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/AddressServiceImpl.java
- src/main/resources/templates/member/address/address.html
- src/main/resources/templates/member/address/addressRegister.html
- src/main/resources/templates/member/address/addressUpdate.html
> [#95] 배송지 view

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/WrappingAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/IndexController.java
- src/main/resources/static/css/main-header.css
- src/main/resources/templates/admin/tag-list.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/layouts/admin_layout.html
- src/main/resources/templates/layouts/main_layout.html
> [#103] 깃 충돌 해결

- src/main/resources/static/js/bookform.js
> [#59] refactor: js에서 image upload url 수정

- src/main/resources/static/js/oauthSignup.js
- src/main/resources/templates/member/oauthSignup.html
> [DEPLOY]  배포

- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/layouts/main_layout.html
> fix: 오타 수정

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/BookAdaptor.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/BookAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/IndexController.java
- src/main/java/com/nhnacademy/inkbridge/front/service/IndexService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/IndexServiceImpl.java
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/member/index.html
카테고리 도서 목록 조회 기능 추가
resolves #59 (이슈가 존재할 경우에만)
> [#59] feat: 카테고리 도서 목록 조회 기능 추가

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/CouponAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/MemberAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/AddressController.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/AdminCouponController.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/AdminTagController.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/CategoryController.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/IndexController.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/MemberController.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/PayRestController.java
- src/main/java/com/nhnacademy/inkbridge/front/jwt/filter/CustomJwtAuthenticationFilter.java
- src/main/java/com/nhnacademy/inkbridge/front/jwt/filter/CustomLoginAuthenticationFilter.java
- src/main/java/com/nhnacademy/inkbridge/front/oauth/handler/CustomOAuthSuccessHandler.java
- src/main/java/com/nhnacademy/inkbridge/front/oauth/service/CustomOAuthUserService.java
- src/main/java/com/nhnacademy/inkbridge/front/oauth/service/OAuthService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/CouponServiceImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/MemberServiceImpl.java
- src/main/resources/application-prod.properties
- src/main/resources/application.properties
- src/main/resources/templates/admin/coupon_create.html
- src/main/resources/templates/admin/coupon_list.html
- src/main/resources/templates/coupon/my_coupon_list.html
- src/main/resources/templates/layouts/main_layout.html
- src/main/resources/templates/member/address/address.html
- src/main/resources/templates/member/address/addressRegister.html
- src/main/resources/templates/member/address/addressUpdate.html
- src/main/resources/templates/member/oauthSignup.html
- src/main/resources/templates/member/signup.html
- src/main/resources/templates/order/orders.html
- src/main/resources/templates/order/pays.html
> [DEPLOY] 배포

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/OrderAdaptor.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/CouponAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/OrderAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/OrderController.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/PayController.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/coupon/MemberCouponReadResponseDto.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/order/OrderCreateResponseDto.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/order/OrderPaymentInfoReadResponseDto.java
- src/main/java/com/nhnacademy/inkbridge/front/service/OrderService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/PayService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/OrderServiceImpl.java
- src/main/resources/static/js/order.js
- src/main/resources/static/js/pay.js
- src/main/resources/templates/order/orders.html
- src/main/resources/templates/order/pays.html
주문서 페이지 선택가능한 포장지만 보이게 수정, 금액 ',' 찍혀서 보이게 수정
resolves 
- #40 (이슈가 존재할 경우에만)
> [#40] 주문서 페이지 선택가능한 포장지만 보이게 수정, 금액 ',' 찍혀서 보이게 수정

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/AddressAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/AddressController.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/address/AddressCreateRequestDto.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/address/AddressUpdateRequestDto.java
- src/main/resources/templates/member/address/addressRegister.html
- src/main/resources/templates/member/address/addressUpdate.html
> [124] 배송지 수정

- src/main/java/com/nhnacademy/inkbridge/front/adaptor/MemberAdaptor.java
- src/main/java/com/nhnacademy/inkbridge/front/adaptor/impl/MemberAdaptorImpl.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/MemberRestController.java
- src/main/java/com/nhnacademy/inkbridge/front/dto/member/request/MemberEmailRequestDto.java
- src/main/java/com/nhnacademy/inkbridge/front/service/MemberService.java
- src/main/java/com/nhnacademy/inkbridge/front/service/impl/MemberServiceImpl.java
- src/main/resources/static/js/oauthSignup.js
- src/main/resources/static/js/signup.js
- src/main/resources/templates/member/oauthSignup.html
- src/main/resources/templates/member/signup.html
> [#102] 회원가입 이메일 중복 추가

- pom.xml
- src/main/java/com/nhnacademy/inkbridge/front/config/DoorayConfig.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/MemberRestController.java
- src/main/java/com/nhnacademy/inkbridge/front/jwt/filter/CustomJwtAuthenticationFilter.java
- src/main/resources/application.properties
- src/main/resources/static/js/signup.js
- src/main/resources/templates/member/signup.html
> [#102] 회원가입 검증 로직 수정

- pom.xml
- src/main/java/com/nhnacademy/inkbridge/front/config/DoorayConfig.java
- src/main/java/com/nhnacademy/inkbridge/front/controller/MemberRestController.java
- src/main/java/com/nhnacademy/inkbridge/front/jwt/filter/CustomJwtAuthenticationFilter.java
- src/main/resources/application.properties
- src/main/resources/static/js/signup.js
- src/main/resources/templates/member/signup.html
> [DEPLOY] 회원가입 수정한 배포입니다.
